from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field


class ArchitectureCapability(str, Enum):
    HIGH_VOLUME_EVENT_INGESTION = "high_volume_event_ingestion"
    DEVICE_TELEMETRY = "device_telemetry"
    EDGE_PROCESSING = "edge_processing"
    STREAM_INGESTION = "stream_ingestion"
    STREAM_PROCESSING = "stream_processing"
    REAL_TIME_ANOMALY_DETECTION = "real_time_anomaly_detection"
    REAL_TIME_ANALYTICS = "real_time_analytics"
    TIME_SERIES_ANALYTICS = "time_series_analytics"
    TIME_SERIES_STORAGE = "time_series_storage"
    DATA_LAKE = "data_lake"
    FEATURE_ENGINEERING = "feature_engineering"
    ML_TRAINING = "ml_training"
    ML_INFERENCE = "ml_inference"
    MODEL_MONITORING = "model_monitoring"
    MODEL_REGISTRY = "model_registry"
    EVENT_DRIVEN_ORCHESTRATION = "event_driven_orchestration"
    HUMAN_APPROVAL = "human_approval"
    EXTERNAL_WORKFLOW_INTEGRATION = "external_workflow_integration"
    INVENTORY_OR_DEPOT_INTEGRATION = "inventory_or_depot_integration"
    EXTERNAL_SYSTEM_INTEGRATION = "external_system_integration"
    ALERTING_NOTIFICATION = "alerting_notification"
    OPERATIONAL_STATE = "operational_state"
    OBSERVABILITY = "observability"
    AUDIT_TRAIL = "audit_trail"
    FULL_AUDIT_TRAIL = "full_audit_trail"
    SECURITY_GOVERNANCE = "security_governance"
    PRIVATE_CONNECTIVITY = "private_connectivity"
    RAG_RETRIEVAL = "rag_retrieval"
    DOCUMENT_INGESTION = "document_ingestion"
    AGENT_TOOL_EXECUTION = "agent_tool_execution"
    CDR_INGESTION = "cdr_ingestion"
    MARKET_DATA_INGESTION = "market_data_ingestion"
    BIOMETRIC_REQUEST_PROCESSING = "biometric_request_processing"
    VIDEO_STREAMING = "video_streaming"
    POS_DATA_INGESTION = "pos_data_ingestion"
    WEATHER_DATA_INGESTION = "weather_data_ingestion"
    BATCH_PROCESSING = "batch_processing"
    HPC_SIMULATION = "hpc_simulation"
    GRAPH_ANALYTICS = "graph_analytics"
    GRAPH_ML_INFERENCE = "graph_ml_inference"
    GNN_INFERENCE = "gnn_inference"
    MONTE_CARLO_SIMULATION = "monte_carlo_simulation"
    SIGNAL_PROCESSING = "signal_processing"
    FEDERATED_LEARNING = "federated_learning"
    DIGITAL_TWIN = "digital_twin"
    BIOMETRIC_MATCHING = "biometric_matching"
    MOLECULAR_GRAPH_MODELING = "molecular_graph_modeling"
    PERSONALIZATION = "personalization"
    ANOMALY_DETECTION = "anomaly_detection"
    AIR_GAPPED_DEPLOYMENT = "air_gapped_deployment"
    SOVEREIGN_DEPLOYMENT = "sovereign_deployment"
    HYBRID_CLOUD = "hybrid_cloud"
    OUTPOSTS_OR_ON_PREM = "outposts_or_on_prem"
    EXCHANGE_COLOCATION = "exchange_colocation"
    FPGA_ACCELERATION = "fpga_acceleration"
    VEHICLE_EDGE_RUNTIME = "vehicle_edge_runtime"
    POLICY_AUTOMATION = "policy_automation"
    OTA_ROLLOUT_ORCHESTRATION = "ota_rollout_orchestration"
    CANARY_DEPLOYMENT = "canary_deployment"
    AUTOMATED_ROLLBACK = "automated_rollback"
    KILL_SWITCH = "kill_switch"
    REGULATORY_REPORT_GENERATION = "regulatory_report_generation"
    GRAPH_STORE = "graph_store"
    LOW_LATENCY_CACHE = "low_latency_cache"
    AUDIT_STORE = "audit_store"
    FEATURE_STORE = "feature_store"
    OBJECT_STORAGE = "object_storage"
    TRANSACTIONAL_STORE = "transactional_store"
    PII_DATA = "pii_data"
    PHI_DATA = "phi_data"
    PCI_OR_FINANCIAL_DATA = "pci_or_financial_data"
    BIOMETRIC_DATA = "biometric_data"
    DATA_RESIDENCY = "data_residency"
    GDPR_COMPLIANCE = "gdpr_compliance"
    HIPAA_COMPLIANCE = "hipaa_compliance"
    GXP_VALIDATION = "gxp_validation"
    FUNCTIONAL_SAFETY = "functional_safety"
    FINANCIAL_MARKET_COMPLIANCE = "financial_market_compliance"
    TELECOM_REGULATORY_COMPLIANCE = "telecom_regulatory_compliance"
    LOW_LATENCY_MEDIA_DELIVERY = "low_latency_media_delivery"
    DRM_ENFORCEMENT = "drm_enforcement"
    GEO_RIGHTS_ENFORCEMENT = "geo_rights_enforcement"
    TARGETED_AD_DECISIONING = "targeted_ad_decisioning"
    INVENTORY_OPTIMIZATION = "inventory_optimization"
    ROUTE_OPTIMIZATION = "route_optimization"
    BID_OPTIMIZATION = "bid_optimization"
    RISK_OPTIMIZATION = "risk_optimization"
    PRE_TRADE_POLICY_BLOCKING = "pre_trade_policy_blocking"
    GEOSPATIAL_ANALYTICS = "geospatial_analytics"
    REINSURANCE_PRICING = "reinsurance_pricing"
    HIGH_AVAILABILITY = "high_availability"
    LOW_LATENCY_CONTROL = "low_latency_control"
    SLA_MONITORING = "sla_monitoring"
    MICROSECOND_LATENCY = "microsecond_latency"


class DeploymentPosture(str, Enum):
    PUBLIC_CLOUD = "public_cloud"
    HYBRID = "hybrid"
    EDGE_AND_CLOUD = "edge_and_cloud"
    AIR_GAPPED_ON_PREM = "air_gapped_on_prem"
    SOVEREIGN_CLOUD = "sovereign_cloud"
    EXCHANGE_COLOCATED = "exchange_colocated"
    CUSTOMER_DC_WITH_AWS_SERVICES = "customer_dc_with_aws_services"


class LatencyClass(str, Enum):
    MICROSECOND = "microsecond"
    SINGLE_DIGIT_MILLISECOND = "single_digit_millisecond"
    SUB_SECOND = "sub_second"
    SECONDS = "seconds"
    MINUTES = "minutes"
    HOURS = "hours"
    BATCH_WINDOW = "batch_window"


class CapabilityExtractionResult(BaseModel):
    capabilities: list[ArchitectureCapability]
    confidence: Literal["low", "medium", "high"]
    extracted_facts: dict = Field(default_factory=dict)
    excluded_patterns: list[str] = Field(default_factory=list)
    reasoning_summary: str
    deployment_posture: list[DeploymentPosture] = Field(default_factory=list)
    latency_class: LatencyClass | None = None

